---
name: Generate all analysis

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 22 * * 4"
  workflow_dispatch:

jobs:
  bundle:
    name: Generate All Analysis Files
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install -r ./requirements.txt
      - run: python ./main.py analyze-snapshot-primary
      - run: python ./main.py analyze-snapshot-all
      - run: python ./main.py analyze-unique-urls
      - run: python ./main.py analyze-unique-websites
      - run: python ./main.py analyze-target-url-list
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update analysis files
