---
name: Generate target url list report

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

jobs:
  bundle:
    name: Generate Target URL List Report
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.9"
      - run: pip install -r ./requirements.txt
      - run: python ./main.py generate-target-url-report
      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # 7.1.0
        with:
          commit_message: Update target-url-list.csv
