---
  name: Generate Urls Missing From Snapshot
  
  # yamllint disable-line rule:truthy
  on:
    schedule:
      - cron: "0 21 * * *"
    workflow_dispatch:
  
  jobs:
    bundle:
      name: Generate Urls Missing From Snapshot
      runs-on: ubuntu-latest
      permissions:
        actions: write
        contents: write
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Setup python
          uses: actions/setup-python@v3
          with:
            python-version: "3.9"
        - name: Install dependencies
          run: pip install -r ./requirements.txt
        - run: python ./main.py generate-missing-target-url-report
        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Update missing target URLs
  