---
  name: Generate website requests report
  
  # yamllint disable-line rule:truthy
  on:
    # schedule:
    #   - cron: "0 14 * * *"
    workflow_dispatch:
  
  jobs:
    bundle:
      name: Generate website requests report
      runs-on: ubuntu-latest
      permissions:
        actions: write
        contents: write
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v3
          with:
            python-version: "3.9"
        - run: pip install -r ./requirements.txt
        - run: python ./main.py website-requests-report
        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Update website requests report
  