---
name: Generate Standards Reports

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

jobs:
  bundle:
    name: Generate Standards Reports
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install -r ./requirements.txt
      - run: python ./main.py generate-standards-report
      - run: python ./main.py generate-standards-bureau-report
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Standards reports
