---
name: Test

# yamllint disable-line rule:truthy
on:
  # Triggers the workflow on push and
  push:
  # Triggers workflow on pull request events for the main branch
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  bundle:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install -r ./requirements.txt
      - name: Test
        run: python3 -m unittest discover tests
